import type { MetadataRoute } from "next";
import { userNavItems } from "@/constants/navigation";
import { PLAY_PACKAGE_ID } from "@/constants/android";

type ShortcutIcon = NonNullable<
  NonNullable<MetadataRoute.Manifest["shortcuts"]>[number]["icons"]
>;

// Next's type misses the first two keys, and wrongly requires `url` on
// related_applications where the spec accepts a bare platform id.
type WebAppManifest = Omit<MetadataRoute.Manifest, "related_applications"> & {
  launch_handler?: { client_mode?: string | string[] };
  share_target?: {
    action: string;
    method?: "GET" | "POST";
    params: { title?: string; text?: string; url?: string };
  };
  related_applications?: { platform: string; id?: string; url?: string }[];
};

// Read out by assistive tech, so each one says what the shortcut does rather
// than repeating its label.
const SHORTCUT_DESCRIPTIONS: Record<string, string> = {
  scan: "Skeniraj barkod proizvoda i usporedi cijene",
  "shopping-lists": "Otvori svoje popise za kupnju",
  watchlist: "Pogledaj proizvode koje pratiš",
  "digital-cards": "Otvori svoje digitalne kartice",
  spending: "Pregledaj svoju potrošnju",
};

// Chrome takes PNG only here; generated by scripts/generate-shortcut-icons.mjs.
// The maskable one is full bleed, since Android otherwise shrinks the tile onto
// a white plate of its own and the glyph ends up too small to read. The "any"
// one carries the brand corner radius for the surfaces that draw it unmasked.
function shortcutIcons(id: string): ShortcutIcon {
  return [
    {
      src: `/brand/shortcuts/${id}.png`,
      sizes: "192x192",
      type: "image/png",
      purpose: "maskable",
    },
    {
      src: `/brand/shortcuts/${id}-any.png`,
      sizes: "192x192",
      type: "image/png",
      purpose: "any",
    },
  ];
}

// Next injects <link rel="manifest"> automatically when this file exists.
export default function manifest(): WebAppManifest {
  // Android shows 3 of these (Chrome keeps a fourth slot for its own "Site
  // settings"), so order is what decides what a phone actually surfaces.
  // Scanning leads: it is the fastest path from launcher to a price.
  const shortcuts = [
    {
      name: "Skeniraj barkod",
      short_name: "Skeniraj",
      description: SHORTCUT_DESCRIPTIONS.scan,
      url: "/?scan=1",
      icons: shortcutIcons("scan"),
    },
    // The rest mirror the nav, minus anything not yet released.
    ...userNavItems
      .filter((item) => !item.comingSoon)
      .map((item) => ({
        name: item.label,
        short_name: item.shortLabel ?? item.label,
        description: SHORTCUT_DESCRIPTIONS[item.id],
        url: item.href,
        icons: shortcutIcons(item.id),
      })),
  ];

  return {
    name: "Disscount - Pronađi najbolje cijene u Hrvatskoj",
    short_name: "Disscount",
    description:
      "Usporedi cijene proizvoda u hrvatskim trgovinama, izradi popise za kupnju i prati popuste.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    lang: "hr",
    dir: "ltr",
    // White matches the iOS launch screens; Chrome generates its own splash from these fields.
    background_color: "#ffffff",
    theme_color: "#ffffff",
    categories: ["shopping", "lifestyle"],
    icons: [
      {
        src: "/brand/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/brand/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Shown in the browser's richer (app-store-like) install dialog.
    screenshots: [
      {
        src: "/screenshots/screenshot-narrow.png",
        sizes: "390x844",
        type: "image/png",
        form_factor: "narrow",
        label: "Usporedba cijena na mobitelu",
      },
      {
        src: "/screenshots/screenshot-wide.png",
        sizes: "1920x1080",
        type: "image/png",
        form_factor: "wide",
        label: "Usporedba cijena na računalu",
      },
    ],
    shortcuts,
    // Shares from other apps land in /share-target and become a product search.
    share_target: {
      action: "/share-target",
      method: "GET",
      params: { title: "title", text: "text", url: "url" },
    },
    // Reuse an open window rather than spawning one per launch, but still go to
    // the shortcut's url. focus-existing would only focus the window and hand
    // the url to launchQueue, which nothing here consumes.
    launch_handler: { client_mode: "navigate-existing" },
    // Lets getInstalledRelatedApps() report whether the Play build is already
    // installed. We still prefer the web install, so the browser prompt stays.
    related_applications: [{ platform: "play", id: PLAY_PACKAGE_ID }],
    prefer_related_applications: false,
  };
}
