import splashScreens from "@/constants/ios-splash-screens.json";

// iOS ignores the web manifest for launch screens and instead uses
// <link rel="apple-touch-startup-image"> tags matched to the device by media
// query. React hoists these into <head>, so an installed app shows a branded
// splash instead of a white flash on launch. Images live in public/splash and
// are generated by scripts/generate-ios-splash.mjs from the same device list.
export default function AppleSplashScreens() {
  return (
    <>
      {splashScreens.map((device) => {
        const pxWidth = device.width * device.ratio;
        const pxHeight = device.height * device.ratio;

        return (
          <link
            key={`${pxWidth}x${pxHeight}`}
            rel="apple-touch-startup-image"
            href={`/splash/apple-splash-${pxWidth}-${pxHeight}.png`}
            media={`screen and (device-width: ${device.width}px) and (device-height: ${device.height}px) and (-webkit-device-pixel-ratio: ${device.ratio}) and (orientation: portrait)`}
          />
        );
      })}
    </>
  );
}
