/**
 * Map store codes to their display names.
 */
export const storeNamesMap: Record<string, string> = {
  plodine: "Plodine",
  tommy: "Tommy",
  konzum: "Konzum",
  lidl: "Lidl",
  studenac: "Studenac",
  spar: "Spar",
  kaufland: "Kaufland",
  metro: "Metro",
  eurospin: "Eurospin",
  jadranka_trgovina: "Jadranka",
  dm: "dm",
  ktc: "KTC",
  trgocentar: "Trgocentar",
  vrutak: "Vrutak",
  zabac: "Žabac",
  ntl: "NTL",
  ribola: "Ribola",
  roto: "Roto",
  boso: "BOSO",
  brodokomerc: "Brodokomerc",
  "trgovina-krk": "Trgovina Krk",
  lorenco: "Lorenco",
};

/**
 * Map location codes to their display names.
 */
export const locationNamesMap: Record<string, string> = {
  "6C KRK": "Krk",
  "A Cista Provo": "Cista Provo",
  "A GORNJA STUBICA": "Gornja Stubica",
  "A Komiža": "Komiža",
  "A Močići": "Močići",
  Banjole: "Banjole",
  Baška: "Baška",
  "Beli Manastir": "Beli Manastir",
  Belišće: "Belišće",
  Benkovac: "Benkovac",
  Bestovje: "Bestovje",
  Bibinje: "Bibinje",
  Bilje: "Bilje",
  Biograd: "Biograd Na Moru",
  "Biograd Na Moru": "Biograd Na Moru",
  Bjelovar: "Bjelovar",
  Borovo: "Borovo",
  Brckovljani: "Brckovljani",
  Brela: "Brela",
  Buje: "Buje",
  Buzet: "Buzet",
  "C Dubrovnik": "Dubrovnik",
  Cavle: "Čavle",
  Cazma: "Čazma",
  Cepin: "Čepin",
  CESTICA: "Čestica",
  Cibaca: "Čibača",
  Cres: "Cres",
  Crikvenica: "Crikvenica",
  Dakovo: "Đakovo",
  Daruvar: "Daruvar",
  Delnice: "Delnice",
  Djakovo: "Đakovo",
  Đakovo: "Đakovo",
  Ðakovo: "Đakovo",
  "Donja Stubica": "Donja Stubica",
  "DONJA STUBICA": "Donja Stubica",
  Donji: "Donji",
  "Donji Kneginec": "Donji Kneginec",
  "Donji Miholjac": "Donji Miholjac",
  Drazice: "Dražice",
  Drenovci: "Drenovci",
  Drniš: "Drniš",
  Dubrovnik: "Dubrovnik",
  "Duga Resa": "Duga Resa",
  "Dugi Rat": "Dugi Rat",
  "Dugo Selo": "Dugo Selo",
  Dugo_Selo: "Dugo Selo",
  Dugopolje: "Dugopolje",
  Durdevac: "Đurđevac",
  Fazana: "Fažana",
  Funtana: "Funtana",
  Garešnica: "Garešnica",
  Gospic: "Gospić",
  Gospić: "Gospić",
  Gradište: "Gradište",
  Gračac: "Gračac",
  Grohote: "Grohote",
  Grubisno: "Grubišno Polje",
  "Grubisno Polje": "Grubišno Polje",
  "Hum Na Sutli": "Hum Na Sutli",
  Hvar: "Hvar",
  Ilok: "Ilok",
  Imotski: "Imotski",
  Ivanec: "Ivanec",
  "Ivanic Grad": "Ivanić-Grad",
  "Ivanić Grad": "Ivanić-Grad",
  "Ivanić-Grad": "Ivanić-Grad",
  Ivankovo: "Ivankovo",
  Jablanovec: "Jablanovec",
  Jarmina: "Jarmina",
  Jastrebarsko: "Jastrebarsko",
  Jelsa: "Jelsa",
  Jezera: "Jezera",
  Kali: "Kali",
  Karlovac: "Karlovac",
  Kastav: "Kastav",
  Kastel: "Kaštel",
  "Kastel Kambelovac": "Kaštel Kambelovac",
  "Kastel Stafilic": "Kaštel Štafilić",
  "Kastel Sucurac": "Kaštel Sućurac",
  "Kaštel Gomilica": "Kaštel Gomilica",
  "Kaštel Lukšić": "Kaštel Lukšić",
  "Kaštel Novi": "Kaštel Novi",
  "Kaštel Stari": "Kaštel Stari",
  "Kaštel Sućurac": "Kaštel Sućurac",
  Kaštela: "Kaštela",
  Knin: "Knin",
  Komolac: "Komolac",
  Koprivnica: "Koprivnica",
  Korenica: "Korenica",
  Korcula: "Korčula",
  Korčula: "Korčula",
  Kostrena: "Kostrena",
  Kotoriba: "Kotoriba",
  Kraljevica: "Kraljevica",
  Krapina: "Krapina",
  "Krapinske Toplice": "Krapinske Toplice",
  Krizevci: "Križevci",
  Križevci: "Križevci",
  Krk: "Krk",
  Kukuljanovo: "Kukuljanovo",
  Kupari: "Kupari",
  Kutina: "Kutina",
  Labin: "Labin",
  Lepoglava: "Lepoglava",
  Lopar: "Lopar",
  Lovran: "Lovran",
  Ludbreg: "Ludbreg",
  Makarska: "Makarska",
  "Mali Lošinj": "Mali Lošinj",
  Malinska: "Malinska",
  MALINSKA: "Malinska",
  "Malinska Krk": "Malinska",
  "Marija Bistrica": "Marija Bistrica",
  "MARIJA BISTRICA": "Marija Bistrica",
  Matulji: "Matulji",
  Medulin: "Medulin",
  Metkovic: "Metković",
  Metković: "Metković",
  Mlini: "Mlini",
  "Mursko Sredisce": "Mursko Središće",
  "Mursko Središće": "Mursko Središće",
  Murter: "Murter",
  Nasice: "Našice",
  Našice: "Našice",
  Nedescina: "Nedešćina",
  Nečujam: "Nečujam",
  Nin: "Nin",
  "Nova Gradiska": "Nova Gradiška",
  "Nova Gradiška": "Nova Gradiška",
  Novalja: "Novalja",
  "Novi Marof": "Novi Marof",
  "Novi Vinodolski": "Novi Vinodolski",
  Novigrad: "Novigrad",
  "Novigrad(Cittanova)": "Novigrad",
  Novska: "Novska",
  Obrovac: "Obrovac",
  Ogulin: "Ogulin",
  "Okrug Gornji": "Okrug Gornji",
  Omiš: "Omiš",
  Omišalj: "Omišalj",
  Opatija: "Opatija",
  Opuzen: "Opuzen",
  Orahovica: "Orahovica",
  Orebic: "Orebić",
  Orebić: "Orebić",
  Oriovac: "Oriovac",
  OROSLAVJE: "Oroslavje",
  Osijek: "Osijek",
  Otok: "Otok",
  Otocac: "Otočac",
  Otočac: "Otočac",
  Ozalj: "Ozalj",
  Pag: "Pag",
  Pakostane: "Pakoštane",
  Pakrac: "Pakrac",
  Pazin: "Pazin",
  Pasman: "Pašman",
  Petrinja: "Petrinja",
  Pirovac: "Pirovac",
  Pitomaca: "Pitomača",
  Pitomača: "Pitomača",
  Pleternica: "Pleternica",
  Ploce: "Ploče",
  Ploče: "Ploče",
  Podstrana: "Podstrana",
  Pomer: "Pomer",
  Popovaca: "Popovača",
  Popovača: "Popovača",
  Porec: "Poreč",
  Poreč: "Poreč",
  Posedarje: "Posedarje",
  Pozega: "Požega",
  Požega: "Požega",
  Pregrada: "Pregrada",
  PREGRADA: "Pregrada",
  Preko: "Preko",
  Prelog: "Prelog",
  Primošten: "Primošten",
  Privlaka: "Privlaka",
  Pula: "Pula",
  PUNAT: "Punat",
  Rab: "Rab",
  "RAVNA GORA": "Ravna Gora",
  Razine: "Šibenik (Ražine)",
  Ražanac: "Ražanac",
  Ražanj: "Ražanj",
  Rijeka: "Rijeka",
  Rogoznica: "Rogoznica",
  Rovinj: "Rovinj",
  Rubeši: "Rubeši",
  Sali: "Sali",
  Samobor: "Samobor",
  "Seget Donji": "Seget Donji",
  Selca: "Selca",
  Selce: "Selce",
  Senj: "Senj",
  Sesvete: "Sesvete",
  "Sesvetski Kraljevec": "Sesvetski Kraljevec",
  Sinj: "Sinj",
  Sisak: "Sisak",
  Slatina: "Slatina",
  "Slavonski brod": "Slavonski Brod",
  "Slavonski Brod": "Slavonski Brod",
  Slavonski_Brod: "Slavonski Brod",
  Slunj: "Slunj",
  Solin: "Solin",
  Split: "Split",
  "Stari Grad": "Stari Grad",
  "Starigrad Paklenica": "Starigrad Paklenica",
  Stobrec: "Stobrec",
  Ston: "Ston",
  Strmec: "Strmec",
  Strožanac: "Strožanac",
  Suhopolje: "Suhopolje",
  Sukosan: "Sukošan",
  Sukošan: "Sukošan",
  Supetar: "Supetar",
  "Sv Ivan Zelina": "Sveti Ivan Zelina",
  "Sv Kriz Zacretje": "Sveti Križ Začretje",
  "Sv.": "Sv.",
  "Sv. Ivan Zelina": "Sveti Ivan Zelina",
  "Sveta Nedelja": "Sveta Nedelja",
  "Sveti Filip I Jakov": "Sveti Filip i Jakov",
  "Sveti Ivan Zelina": "Sveti Ivan Zelina",
  "Sveti Križ Začretje": "Sveti Križ Začretje",
  "T Zaton": "Zaton",
  Tar: "Tar",
  Tkon: "Tkon",
  Tribunj: "Tribunj",
  Trilj: "Trilj",
  "Trnovec Bartolovečki": "Trnovec Bartolovečki",
  Trogir: "Trogir",
  Umag: "Umag",
  "Umag-Umago": "Umag",
  Valpovo: "Valpovo",
  "Varazdinske Toplice": "Varaždinske Toplice",
  Varazdin: "Varaždin",
  Varaždin: "Varaždin",
  "Vela Luka": "Vela Luka",
  "Velika Gorica": "Velika Gorica",
  Velika_Gorica: "Velika Gorica",
  "Veliko Trgovišće": "Veliko Trgovišće",
  Vinkovci: "Vinkovci",
  Vir: "Vir",
  Virovitica: "Virovitica",
  VIROVITICA: "Virovitica",
  Vis: "Vis",
  Viskovo: "Viškovo",
  Viškovo: "Viškovo",
  Vodice: "Vodice",
  Vodnjan: "Vodnjan",
  Volosko: "Volosko",
  Vrbovec: "Vrbovec",
  Vrpolje: "Vrpolje",
  Vrsar: "Vrsar",
  Vrsi: "Vrsi",
  Vukovar: "Vukovar",
  Zabok: "Zabok",
  Zadar: "Zadar",
  Zagreb: "Zagreb",
  "Zagreb Blato": "Zagreb (Blato)",
  Zagreb_Dubec: "Zagreb (Dubec)",
  "Zagreb Novi Zagreb": "Zagreb (Novi Zagreb)",
  "Zagreb - Sesvete": "Zagreb (Sesvete)",
  Zaostrog: "Zaostrog",
  Zaprešic: "Zaprešić",
  Zapresic: "Zaprešić",
  Zaprešić: "Zaprešić",
  Zlatar: "Zlatar",
  "Zlatar Bistrica": "Zlatar Bistrica",
  Cakovec: "Čakovec",
  "Čatrnja Rakovica": "Čatrnja (Rakovica)",
  Čepin: "Čepin",
  Đurđevac: "Đurđevac",
  Šestenovac: "Šestanovac",
  Sibenik: "Šibenik",
  "Šibenik-Ražine": "Šibenik (Ražine)",
  Zminj: "Žminj",
  Zupanja: "Županja",
  Županja: "Županja",
};
